### PR TITLE
Add checkers

### PR DESCRIPTION
**Pull request by Kenrou7**

### CODE REVIEW

**Comment by Kenrou7** [comment]
@RodrigoCSolari for some reason, the account is below the dot. It doesn't seem to be a space thing
image

**Comment by Kenrou7** [comment]
When game is active, the displayed token is the contract. It should be the token name (NEAR, Cheddar, NEKO)

image

**Comment by Kenrou7** [comment]
Logged in with meteor wallet, if I make a move, then reject closing the meteor wallet modal, it crashes

image

**Comment by Kenrou7** [comment]
After making a move it looks like this
image

**Comment by Kenrou7** [comment]
In this scenario I can use double jump, making the move d4 b6 d8
image

But the transaction is sending another move
image

**Comment by Kenrou7** [comment]
If I click `Double jump` and I regret my move, I don't have a way to cancel.

**Comment by Kenrou7** [comment]
FE allows men (pieces that are not promoted) to move backwards. Contract says illegal move as it should say
image

**Comment by Kenrou7** [comment]
When winning, there is no modal nor anything that indicates I've won.

**Comment by Kenrou7** [comment]
On rules, the word `don't` is spelled with " instead of '
image

**Comment by RodrigoCSolari** [comment]
> @RodrigoCSolari for some reason, the account is below the dot. It doesn't seem to be a space thing image

resuelto

**Comment by RodrigoCSolari** [comment]
> When game is active, the displayed token is the contract. It should be the token name (NEAR, Cheddar, NEKO)
> 
> image

resuelto

**Comment by RodrigoCSolari** [comment]
@Kenrou7 all bugs were fixed

**Pull request merged**
